language: node_js

notifications:
  email:
    on_success: never
    on_failure: always

node_js:
  - "8.9.4"

services:
  - mongodb

cache:
  directories:
  - node_modules

script:
  - wget https://raw.githubusercontent.com/Frost-Dev/Frost/master/config.json
  - npm run test
