language: node_js

node_js:
  - "7.7.0"

services:
  - mongodb

cache:
  directories:
  - node_modules

script:
  - wget https://raw.githubusercontent.com/Frost-Dev/Frost/master/config.json
  - npm run test
