language: node_js

notifications:
  email:
    on_success: never
    on_failure: always

node_js:
  - "8.9.4"

services:
  - mongodb
  - redis-server

cache:
  directories:
  - node_modules

script:
  - npm run generate-configs
  - npm run test
