language: node_js

notifications:
  email:
    on_success: never
    on_failure: always

node_js:
  - "7.7.0"

services:
  - mongodb

cache:
  directories:
  - node_modules

script:
  - wget https://raw.githubusercontent.com/Frost-Dev/Frost/master/config.json
  - npm run rebuild
  - npm run test
